bosh_kubernetes_cpi/dependencies.source.tgz:
  size: 301955068
  sha: 9557b51ff708dfbc91e8c17ce5e055b91fd5151a
ghc/ghc-8.0.1-x86_64-apple-darwin.tar.xz:
  size: 118496652
  object_id: 8804f92b-2a54-431a-6eb0-12e9aca2d82c
  sha: e7a1c558a095afbc4fb514256be940ddb0f23a29
ghc/ghc-8.0.1-x86_64-centos67-linux.tar.xz:
  size: 112386128
  object_id: e7c2f2ec-c974-4b75-7c05-04818f97abbc
  sha: 1735fc722cc1c72b446534e8d021d09f383856ff
ghc/ghc-8.0.1-x86_64-deb8-linux.tar.xz:
  size: 112955808
  object_id: c57f0530-81b9-4936-6b3d-0b255a5079d1
  sha: 4a313d073982901a1ce8477386a61e4673511006
gmp/gmp-5.1.3.tar.xz:
  size: 1818812
  sha: 12cfe0911d64fcbd85835df9ddc18c99af8f9a45
stack/stack-1.3.2-linux-x86_64-static.tar.gz:
  size: 6047156
  object_id: 354d3d8c-6a91-4b4a-4d62-de81e40becd4
  sha: bf7125e47730f2dab2d6b4dc00513201011fd90f
stack/stack-1.3.2-osx-x86_64.tar.gz:
  size: 12836415
  object_id: bff01e13-6700-4bf3-4f83-e3dcab994ca0
  sha: e8a9db496c0a6cc86c7d0399d2f03b3e08c966eb
